export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  author: string
  coverImage: string
  featured?: boolean
  content: string[]
}

function cover(slug: string) {
  return `/blog/${slug}.svg`
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'zero-waste-starts-in-pakistani-kitchens',
    title: 'Zero Waste Starts in Pakistani Kitchens',
    excerpt: 'How source segregation at home can reduce landfill pressure in Lahore, Karachi, and Islamabad — one household at a time.',
    category: 'Movement',
    date: 'Jun 8, 2026',
    readTime: '5 min',
    author: 'Areeba Syed',
    featured: true,
    coverImage: cover('zero-waste-starts-in-pakistani-kitchens'),
    content: [
      'Every day, Pakistani households generate organic waste that could be composted, recycled, or safely separated — but most of it still ends up mixed in one bag headed for landfill.',
      'Eco Zindagi was founded on a simple belief: change starts at the kitchen counter. When families separate organics, dry recyclables, and reject waste at the source, the entire waste chain becomes cleaner, cheaper, and more circular.',
      'Our Basic Zero-Waste Bin and Eco Caddy Mini are designed specifically for Pakistani apartment sizes and daily cooking habits — from daal and roti scraps to fruit peels and tea leaves.',
      'Cities like Lahore and Karachi are facing mounting waste crises. Household-level segregation is not a luxury — it is the most scalable first step any family can take today.',
      'Start small: keep a 5L caddy on your counter, empty it into your main bin weekly, and sprinkle BrownBoost to control moisture and odor.',
    ],
  },
  {
    slug: 'bioloop-60-inside-the-engineering',
    title: 'Inside BioLoop-60: Engineering for Indoor Composting',
    excerpt: 'A look at charcoal filtration, modular drawers, and the sensor layer that makes clean-tech waste management possible at home.',
    category: 'Product',
    date: 'Jun 5, 2026',
    readTime: '7 min',
    author: 'Eco Zindagi Team',
    featured: true,
    coverImage: cover('bioloop-60-inside-the-engineering'),
    content: [
      'BioLoop-60 is Eco Zindagi\'s flagship — a smart household system that brings industrial-grade waste separation into a form factor designed for modern Pakistani homes.',
      'The drawer architecture separates 8L of organics, 12L of dry recyclables, 4L of reject waste, and a 28L compost starter chamber. Each stream stays isolated from collection to processing.',
      'Charcoal filtration and bio-inoculum support keep decomposition odor-free and indoor-friendly — solving the number one reason families avoid composting at home.',
      'An IoT sensor layer monitors fill levels and connects to the Eco Zindagi app for insights, maintenance alerts, and EcoBucks rewards.',
      'Every component is modular and serviceable — from the OdorGuard cartridge to charcoal filter refills.',
    ],
  },
  {
    slug: 'brownboost-and-the-carbon-balance',
    title: 'Why BrownBoost Matters for Wet Kitchen Waste',
    excerpt: 'Balancing moisture and carbon in your caddy keeps odors down and makes composting smoother for everyday families.',
    category: 'Guides',
    date: 'May 28, 2026',
    readTime: '4 min',
    author: 'Eco Zindagi Team',
    featured: true,
    coverImage: cover('brownboost-and-the-carbon-balance'),
    content: [
      'Wet kitchen waste is the hardest part of home composting. High moisture leads to smells, flies, and slow breakdown.',
      'BrownBoost is our 2 KG carbon-balance refill made from cocopeat, rice-husk biochar, and dry browns. Sprinkle it over wet organics to absorb moisture and restore carbon balance.',
      'At just Rs. 549, it is the most affordable way to keep your caddy fresh between emptying cycles.',
      'Use BrownBoost with any Eco Zindagi caddy or bin — Eco Caddy Mini, Basic Zero-Waste Bin, or BioLoop systems.',
    ],
  },
  {
    slug: 'community-bioloop-pilot-schools',
    title: 'Community BioLoop 120L: Piloting Zero-Waste in Schools',
    excerpt: 'Institutional-scale segregation and supplemental biogas — built for campuses, cafés, and housing societies across Pakistan.',
    category: 'Impact',
    date: 'May 20, 2026',
    readTime: '6 min',
    author: 'Areeba Syed',
    featured: true,
    coverImage: cover('community-bioloop-pilot-schools'),
    content: [
      'Schools and universities generate hundreds of kilograms of food waste daily. Community BioLoop 120L is our answer — an institutional zero-waste and supplemental biogas pilot unit.',
      'With 120L daily input capacity and 0.2–0.4 m³ biogas output per day, it turns cafeteria waste into clean energy and nutrient-rich digestate.',
      'We are piloting with campuses across Pakistan to prove that community-scale circular systems are viable, affordable, and impactful.',
      'Lockable access, odor-control filtration, and mobile caster options make it suitable for schools, housing societies, and commercial cafés.',
    ],
  },
  {
    slug: 'zevyer-partnership-clean-tech',
    title: 'Eco Zindagi × Zevyer: Building Clean-Tech for Pakistan',
    excerpt: 'Our partnership with Zevyer brings hardware expertise and startup velocity to sustainable products made for local households.',
    category: 'Startup',
    date: 'May 12, 2026',
    readTime: '4 min',
    author: 'Sadeeq Khan',
    coverImage: cover('zevyer-partnership-clean-tech'),
    content: [
      'Eco Zindagi and Zevyer share a mission: build hardware that solves real problems for Pakistani households — fast.',
      'Sadeeq Khan, founder of Zevyer, partners with Eco Zindagi on prototyping, manufacturing strategy, and bringing clean-tech products from concept to market.',
      'This partnership lets Eco Zindagi move at startup speed while maintaining the engineering rigor that waste-management hardware demands.',
      'Together, we are building the product pipeline that will define sustainable living in Pakistan for the next decade.',
    ],
  },
  {
    slug: 'growmix-from-waste-to-soil',
    title: 'From Waste to Soil: The Story Behind GrowMix',
    excerpt: 'Compost blend, cocopeat, and biochar — turning circular waste streams into premium growing media for home gardens.',
    category: 'Circular Economy',
    date: 'May 3, 2026',
    readTime: '5 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('growmix-from-waste-to-soil'),
    content: [
      'GrowMix closes the loop. What starts as kitchen waste can end as nutrient-rich soil for your home garden.',
      'Our 10 KG pack blends compost, cocopeat, biochar, and rice husk into a light, fluffy, well-draining growing media with pH 6.5–7.5.',
      'Made with love for a greener Pakistan — GrowMix is ideal for potted plants, kitchen gardens, vegetable beds, and flowering plants.',
      'Available in 10 KG packs with bulk options for community projects and commercial growers.',
    ],
  },
  {
    slug: 'source-segregation-guide-pakistan',
    title: 'The Complete Source Segregation Guide for Pakistan',
    excerpt: 'A practical room-by-room guide to separating organics, recyclables, and reject waste in Pakistani homes.',
    category: 'Guides',
    date: 'Apr 28, 2026',
    readTime: '6 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('source-segregation-guide-pakistan'),
    content: [
      'Source segregation means sorting waste where it is created — before it leaves your home. This single habit can cut landfill-bound waste by up to 60%.',
      'In the kitchen: fruit peels, vegetable scraps, tea leaves, and leftover food go to organics. Plastic wrappers and packaging go to dry recyclables.',
      'In the bathroom: sanitary waste goes to the reject stream — never mixed with organics or recyclables.',
      'Use labeled bins or the Eco Zindagi three-drawer system to make segregation automatic for every family member.',
      'Start with one week of conscious sorting. Most families form the habit within 14 days.',
    ],
  },
  {
    slug: 'odor-control-indoor-composting',
    title: 'Odor Control: Making Indoor Composting Work in Pakistani Homes',
    excerpt: 'Charcoal filters, ventilation design, and BrownBoost — the science behind smell-free home composting.',
    category: 'Product',
    date: 'Apr 22, 2026',
    readTime: '5 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('odor-control-indoor-composting'),
    content: [
      'The biggest barrier to home composting in Pakistan is odor — especially in apartments and shared housing.',
      'Eco Zindagi solves this with a three-layer approach: ventilated lids, activated carbon filtration, and carbon-balance refills.',
      'Our OdorGuard Cartridge uses coconut shell activated carbon to trap ammonia, hydrogen sulfide, and VOCs for 30–45 days.',
      'Replace cartridges on schedule and sprinkle BrownBoost over wet organics to maintain the carbon-to-nitrogen balance.',
      'With the right system, indoor composting is cleaner than leaving food waste in an open kitchen bin.',
    ],
  },
  {
    slug: 'housing-societies-zero-waste',
    title: 'How Housing Societies Can Go Zero-Waste in 90 Days',
    excerpt: 'A step-by-step playbook for society management teams to deploy Eco Zindagi systems across residential blocks.',
    category: 'Partnerships',
    date: 'Apr 15, 2026',
    readTime: '8 min',
    author: 'Areeba Syed',
    featured: true,
    coverImage: cover('housing-societies-zero-waste'),
    content: [
      'Housing societies in Lahore, Islamabad, and Karachi are uniquely positioned to lead Pakistan\'s zero-waste transition.',
      'Phase 1 (Week 1–2): Site assessment — map waste collection points, common areas, and household count with Eco Zindagi team.',
      'Phase 2 (Week 3–6): Deploy BioLoop-60 units in participating homes and install Community BioLoop 120L at central collection points.',
      'Phase 3 (Week 7–10): Train residents and staff on segregation, filter replacement, and maintenance schedules.',
      'Phase 4 (Week 11–12): Measure impact — waste diverted, odor complaints reduced, and community engagement scores.',
      'Contact our partnerships team to start your society\'s green transformation.',
    ],
  },
  {
    slug: 'smart-cities-waste-management',
    title: 'Smart Cities Need Smart Waste: A Vision for Pakistan',
    excerpt: 'How municipalities can deploy community-scale BioLoop systems to build cleaner, greener urban infrastructure.',
    category: 'Partnerships',
    date: 'Apr 8, 2026',
    readTime: '7 min',
    author: 'Areeba Syed',
    coverImage: cover('smart-cities-waste-management'),
    content: [
      'Pakistan\'s cities generate millions of tons of waste annually — and most of it is never segregated at source.',
      'Smart waste management starts with infrastructure at the community level: segregated collection, local processing, and circular outputs.',
      'Community BioLoop 120L units can be deployed in markets, schools, parks, and public spaces — creating a network of clean processing nodes.',
      'Sensor monitoring and data dashboards help city administrators track fill levels, optimize collection routes, and measure environmental impact.',
      'Eco Zindagi partners with municipal teams and development authorities to design city-scale pilot programs.',
    ],
  },
  {
    slug: 'school-cafeteria-waste-solutions',
    title: 'School Cafeteria Waste: From Problem to Biogas',
    excerpt: 'How schools can turn daily food waste into energy and learning opportunities with Community BioLoop.',
    category: 'Impact',
    date: 'Mar 30, 2026',
    readTime: '5 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('school-cafeteria-waste-solutions'),
    content: [
      'A single school cafeteria can generate 50–100 kg of food waste per day. Most of it ends up in landfills.',
      'Community BioLoop 120L processes cafeteria organics on-site — producing supplemental biogas and nutrient-rich digestate.',
      'Students learn about circular economy, anaerobic digestion, and environmental science through hands-on engagement.',
      'Schools save on waste hauling costs while demonstrating leadership in sustainability to parents and communities.',
      'Contact Eco Zindagi for school pilot program pricing and deployment timelines.',
    ],
  },
  {
    slug: 'biogas-basics-home-and-community',
    title: 'Biogas Basics: From Kitchen Scraps to Clean Energy',
    excerpt: 'Understanding how anaerobic digestion works in BioLoop systems — for homes and communities.',
    category: 'Education',
    date: 'Mar 22, 2026',
    readTime: '6 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('biogas-basics-home-and-community'),
    content: [
      'Biogas is produced when organic matter breaks down in an oxygen-free (anaerobic) environment.',
      'In Community BioLoop 120L, daily food waste input of up to 120L can produce 0.2–0.4 cubic meters of biogas per day.',
      'This low-pressure biogas can supplement cooking fuel, power small appliances, or be flared safely.',
      'The byproduct — digestate — is a nutrient-rich liquid fertilizer ideal for school gardens and community green spaces.',
      'Biogas at the community scale is a practical step toward energy independence and waste valorization in Pakistan.',
    ],
  },
  {
    slug: 'composting-in-apartments',
    title: 'Composting in Pakistani Apartments: Yes, It\'s Possible',
    excerpt: 'Space-saving strategies for apartment dwellers who want to compost without smell or mess.',
    category: 'Guides',
    date: 'Mar 15, 2026',
    readTime: '4 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('composting-in-apartments'),
    content: [
      'Living in an apartment does not mean you cannot compost. Modern compact systems are designed for small spaces.',
      'Start with an Eco Caddy Mini (5L) on your kitchen counter for daily organics collection.',
      'Upgrade to a Basic Zero-Waste Bin or BioLoop-60 for full three-stream segregation and odor-controlled processing.',
      'Use BrownBoost after every caddy empty to control moisture. Replace OdorGuard cartridges every 30–45 days.',
      'Balcony gardens love the compost output — GrowMix makes an excellent growing medium for your plants.',
    ],
  },
  {
    slug: 'activated-carbon-filters-explained',
    title: 'Activated Carbon Filters: How They Keep Your Home Fresh',
    excerpt: 'The science behind Eco Zindagi\'s odor-control cartridges and when to replace them.',
    category: 'Product',
    date: 'Mar 8, 2026',
    readTime: '4 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('activated-carbon-filters-explained'),
    content: [
      'Activated carbon has millions of tiny pores that trap odor molecules, ammonia, hydrogen sulfide, and VOCs.',
      'Eco Zindagi uses coconut shell activated carbon — a natural, renewable material with high adsorption capacity.',
      'Our OdorGuard Cartridge and Activated Carbon Filter are designed as drop-in replacements — no tools required.',
      'Replace every 30–45 days depending on usage. Heavy kitchen waste periods may need more frequent changes.',
      'At Rs. 349–399 per cartridge, odor control costs less than a cup of chai per week.',
    ],
  },
  {
    slug: 'circular-economy-pakistan-2026',
    title: 'Circular Economy in Pakistan: Where We Are in 2026',
    excerpt: 'An honest look at Pakistan\'s circular economy progress and the role clean-tech startups play.',
    category: 'Movement',
    date: 'Feb 28, 2026',
    readTime: '7 min',
    author: 'Areeba Syed',
    coverImage: cover('circular-economy-pakistan-2026'),
    content: [
      'Pakistan\'s circular economy is still in its early stages — but momentum is building fast.',
      'Startups like Eco Zindagi are proving that circular hardware can be designed, manufactured, and deployed locally.',
      'Key enablers: household segregation habits, institutional partnerships, and affordable consumable refills.',
      'Challenges remain: waste collection infrastructure, policy support, and consumer awareness.',
      'Every household that segregates, every society that pilots, and every school that composts moves the needle.',
    ],
  },
  {
    slug: 'eco-caddy-mini-setup-guide',
    title: 'Eco Caddy Mini: Setup Guide for First-Time Users',
    excerpt: 'Unbox, install your filter, and start collecting kitchen organics in under 10 minutes.',
    category: 'Guides',
    date: 'Feb 20, 2026',
    readTime: '3 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('eco-caddy-mini-setup-guide'),
    content: [
      'Your Eco Caddy Mini arrives ready to use. Here is how to set it up in minutes.',
      'Step 1: Insert an OdorGuard Cartridge into the lid filter slot.',
      'Step 2: Place the caddy on your kitchen counter near your prep area.',
      'Step 3: Line the inner bucket with a compostable bag (optional) and start collecting organics.',
      'Step 4: Empty every 2–3 days into your main bin. Sprinkle BrownBoost to control moisture.',
      'The 5L capacity is perfect for 2–4 person households.',
    ],
  },
  {
    slug: 'dry-waste-recycling-at-home',
    title: 'Dry Waste Recycling: What Goes in the Blue Stream',
    excerpt: 'Paper, plastic, metal, and glass — a clear guide to dry recyclables for Pakistani households.',
    category: 'Guides',
    date: 'Feb 12, 2026',
    readTime: '5 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('dry-waste-recycling-at-home'),
    content: [
      'Dry recyclables are materials that can be processed and reused — but only if they stay clean and separate.',
      'Include: clean paper, cardboard, plastic bottles, metal cans, and glass containers.',
      'Exclude: food-contaminated packaging, greasy paper, and mixed-material items.',
      'Rinse containers briefly before placing in your dry recyclables drawer or bin.',
      'In BioLoop-60, the 12L dry recyclables drawer keeps this stream separate from organics and reject waste.',
    ],
  },
  {
    slug: 'women-led-clean-tech-pakistan',
    title: 'Women-Led Clean-Tech: Building Eco Zindagi',
    excerpt: 'Founder Areeba Syed on building a sustainable hardware startup in Pakistan as a woman entrepreneur.',
    category: 'Startup',
    date: 'Feb 5, 2026',
    readTime: '6 min',
    author: 'Areeba Syed',
    coverImage: cover('women-led-clean-tech-pakistan'),
    content: [
      'Eco Zindagi was founded by Areeba Syed with a clear mission: make zero-waste living practical for every Pakistani household.',
      'Building hardware as a woman entrepreneur in Pakistan comes with unique challenges — and unique strengths.',
      'Our team prioritizes products that work in real kitchens, real apartments, and real communities — not just in labs.',
      'We believe clean-tech should be accessible, affordable, and designed with empathy for everyday families.',
      'Eco Zindagi is proof that women-led startups can build the physical infrastructure for a greener Pakistan.',
    ],
  },
  {
    slug: 'lahore-waste-crisis-solutions',
    title: 'Lahore\'s Waste Crisis: Practical Solutions That Work',
    excerpt: 'From smog to landfills — how Lahore households and societies can take action today.',
    category: 'Impact',
    date: 'Jan 28, 2026',
    readTime: '6 min',
    author: 'Eco Zindagi Team',
    coverImage: cover('lahore-waste-crisis-solutions'),
    content: [
      'Lahore faces a dual environmental crisis: air pollution and uncontrolled waste dumping.',
      'When organic waste decomposes in open landfills, it releases methane — a potent greenhouse gas that worsens air quality.',
      'Source segregation at the household level directly reduces the volume of waste reaching landfills.',
      'Housing societies in DHA, Bahria Town, and Model Town can pilot Community BioLoop systems for centralized processing.',
      'Individual families can start with an Eco Caddy Mini today — small actions compound across a city of 14 million.',
    ],
  },
  {
    slug: 'institutional-partnership-playbook',
    title: 'The Institutional Partnership Playbook',
    excerpt: 'Everything societies, schools, and city teams need to know before partnering with Eco Zindagi.',
    category: 'Partnerships',
    date: 'Jan 15, 2026',
    readTime: '8 min',
    author: 'Areeba Syed',
    coverImage: cover('institutional-partnership-playbook'),
    content: [
      'Institutional partnerships are the fastest way to scale zero-waste infrastructure across Pakistan.',
      'Who can partner: housing society management, municipal authorities, school administrations, and commercial developers.',
      'What we provide: site assessment, product deployment, staff training, maintenance support, and impact reporting.',
      'Timeline: most society pilots go live within 90 days from first contact to full deployment.',
      'Investment: pricing scales with community size — contact our team for a custom quote.',
      'Get started: visit ecozindagi.pk/partnerships or WhatsApp our team at +92 335 9463244.',
    ],
  },
]

export function getFeaturedPosts(): BlogPost[] {
  return blogPosts.filter((p) => p.featured)
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug)
}
